version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
  server:
    build:
      target: arranger-server
    environment:
      - SERVER_PORT=6060
      - ARRANGER_PROJECT_ID=testproject
      - ELASTICSEARCH=http://elasticsearch:9200
    depends_on:
      - elasticsearch
  admin_server:
    build:
      target: arranger-admin-server
    environment:
      - ADMIN_SERVER_PORT=5050
      - ELASTICSEARCH=http://elasticsearch:9200
    depends_on:
      - server
      - elasticsearch
  admin_ui:
    build:
      target: arranger-admin-ui
    environment:
      - REACT_APP_ARRANGER_ADMIN_ROOT=http://admin_server:5050/admin/graphql
      - HOST=0.0.0.0
      - PORT=4000
    depends_on:
      - admin_server
