name: CI pipeline server filter

on:
  push:
    branches:
      - patched-version
    paths:
      - 'modules/server-filter/**'
  pull_request:
    branches:
      - patched-version
    paths:
      - 'modules/server-filter/**'

jobs:

  build_and_publish:
   uses: PilotDataPlatform/shared-ci-tools/.github/workflows/reusable_build_and_publish_pilot.yml@main
   with:
     matrix_config: '["arranger-server-filter"]'
     docker_registry: 'pilotdataplatform.azurecr.io'
     service_name: 'arranger-server'
   secrets: inherit

  trigger_deployment:
    needs: [build_and_publish]
    uses: PilotDataPlatform/shared-ci-tools/.github/workflows/reusable_trigger_deployment_pilot.yml@main
    with:
      service_name: 'arranger-server-filter'
      app_version: "${{needs.build_and_publish.outputs.app_version}}"
    secrets: inherit
